### ISSUE TITLE
Object of class PHPStan\Rules\RuleErrors\RuleError1 could not be converted to string

### ISSUE THREAD

**Issue by mimmi20** [pepakriz/phpstan-exception-rules#149]
# Bug report

## Versions
> pepakriz/phpstan-exception-rules 0.11.7
> PHPStan - PHP Static Analysis Tool 0.12.94

## Error

Internal error: Object of class PHPStan\Rules\RuleErrors\RuleError1 could not be converted to string
         Run PHPStan with --debug option and post the stack trace to:
         https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md

```shell
C:\Users\Besitzer\Documents\GitHub\navigation-helper-converttopages\src\ConvertToPages.php
Uncaught Error: Object of class PHPStan\Rules\RuleErrors\RuleError1 could not be converted to string in C:\Users\Besitzer\Documents\GitHub\navigation-helper-converttopages\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php:469
#0 C:\Users\Besitzer\Documents\GitHub\navigation-helper-converttopages\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php(469): array_unique(Array)
#1 C:\Users\Besitzer\Documents\GitHub\navigation-helper-converttopages\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php(223): Pepakriz\PHPStanExceptionRules\Rules\ThrowsPhpDocRule->processExprTraversing(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Analyser\MutatingScope), false)
#2 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(69): Pepakriz\PHPStanExceptionRules\Rules\ThrowsPhpDocRule->processNode(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope))
#3 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(91): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope))
#4 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(404): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope))
#5 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(312): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope))
#6 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#7 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(545): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#8 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#9 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(419): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#10 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#11 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(503): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#12 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#13 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(469): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(222): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(149): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile('C:\\Users\\Besitz...', Array, Object(PHPStan\Rules\Registry), NULL)
#17 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#18 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(148): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, 'C:\\Users\\Besitz...', NULL, NULL, Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#19 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(79): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, 'C:\\Users\\Besitz...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#20 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(157): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, 'C:\\Users\\Besitz...', Array, Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#21 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#22 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_8f2e45ccf\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#23 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#24 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->doRun(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#25 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->run()
#26 phar://C:/Users/Besitzer/Documents/GitHub/navigation-helper-converttopages/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_8f2e45ccf\{closure}()
#27 C:\Users\Besitzer\Documents\GitHub\navigation-helper-converttopages\vendor\phpstan\phpstan\phpstan(8): require('phar://C:/Users...')
#28 {main}
```

### Code snippet that reproduces the problem

This is the code of the file where the error is thrown.

```php
<?php
/**
 * This file is part of the mimmi20/mezzio-navigation-helpers package.
 *
 * Copyright (c) 2021, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace Mimmi20\NavigationHelper\ConvertToPages;

use Laminas\Log\Logger;
use Laminas\Navigation\AbstractContainer;
use Laminas\Navigation\Page\AbstractPage;
use Laminas\Stdlib\ArrayUtils;
use Mezzio\Navigation\ContainerInterface;
use Mezzio\Navigation\Exception\InvalidArgumentException;
use Mezzio\Navigation\Page\PageFactoryInterface;
use Mezzio\Navigation\Page\PageInterface;
use Traversable;

use function array_map;
use function is_array;
use function is_numeric;
use function is_string;
use function key;

final class ConvertToPages implements ConvertToPagesInterface
{
    private Logger $logger;

    /**
     * @var \Mezzio\Navigation\Page\PageFactoryInterface|null
     */
    private ?PageFactoryInterface $pageFactory = null;

    /**
     * @param \Laminas\Log\Logger                          $logger
     * @param \Mezzio\Navigation\Page\PageFactoryInterface|null $pageFactory
     */
    public function __construct(Logger $logger, ?PageFactoryInterface $pageFactory)
    {
        $this->logger      = $logger;
        $this->pageFactory = $pageFactory;
    }

    /**
     * Converts a $mixed value to an array of pages
     *
     * @param int|array<int|string, array<string>|string>|AbstractPage|AbstractContainer|ContainerInterface|PageInterface|string|Traversable $mixed     mixed value to get page(s) from
     * @param bool                                                                                        $recursive whether $value should be looped if it is an array or a config
     *
     * @return array<int, PageInterface|AbstractPage>
     *
     * @throws \Laminas\Stdlib\Exception\InvalidArgumentException
     */
    public function convert($mixed, bool $recursive = true): array
    {
        if ($mixed instanceof PageInterface || $mixed instanceof AbstractPage) {
            // value is a page instance; return directly
            return [$mixed];
        }

        if ($mixed instanceof ContainerInterface || $mixed instanceof AbstractContainer) {
            // value is a container; return pages in it
            $pages = [];

            foreach ($mixed as $page) {
                $pages[] = $page;
            }

            return $pages;
        }

        if (is_string($mixed)) {
            // value is a string; make a URI page
            try {
                if (null !== $this->pageFactory) {
                    $page = $this->pageFactory->factory(
                        [
                            'type' => 'uri',
                            'uri' => $mixed,
                        ]
                    );
                } else {
                    $page = AbstractPage::factory(
                        [
                            'type' => 'uri',
                            'uri' => $mixed,
                        ]
                    );
                }

                return [$page];
            } catch (InvalidArgumentException | \Laminas\Navigation\Exception\InvalidArgumentException $e) {
                $this->logger->err($e);

                return [];
            }
        }

        if ($mixed instanceof Traversable) {
            $mixed = ArrayUtils::iteratorToArray($mixed);
        }

        if (is_array($mixed) && [] !== $mixed) {
            if ($recursive && is_numeric(key($mixed))) {
                // first key is numeric; assume several pages
                return array_map(
                    /**
                     * @return PageInterface|AbstractPage
                     */
                    function ($value) {
                        [$page] = $this->convert($value, false);

                        return $page;
                    },
                    $mixed
                );
            }

            // pass array to factory directly
            try {
                if (null !== $this->pageFactory) {
                    $page = $this->pageFactory->factory($mixed);
                } else {
                    $page = AbstractPage::factory($mixed);
                }

                return [$page];
            } catch (InvalidArgumentException | \Laminas\Navigation\Exception\InvalidArgumentException $e) {
                $this->logger->err($e);
            }
        }

        // nothing found
        return [];
    }
}

```

If I change the file to the following content, the exception is not thrown.

```php
<?php
/**
 * This file is part of the mimmi20/mezzio-navigation-helpers package.
 *
 * Copyright (c) 2021, Thomas Mueller <mimmi20@live.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace Mimmi20\NavigationHelper\ConvertToPages;

use Laminas\Log\Logger;
use Laminas\Navigation\AbstractContainer;
use Laminas\Navigation\Page\AbstractPage;
use Laminas\Stdlib\ArrayUtils;
use Mezzio\Navigation\ContainerInterface;
use Mezzio\Navigation\Exception\InvalidArgumentException;
use Mezzio\Navigation\Page\PageFactoryInterface;
use Mezzio\Navigation\Page\PageInterface;
use Traversable;

use function array_map;
use function is_array;
use function is_numeric;
use function is_string;
use function key;

final class ConvertToPages implements ConvertToPagesInterface
{
    private Logger $logger;

    /**
     * @var \Mezzio\Navigation\Page\PageFactoryInterface|null
     */
    private ?PageFactoryInterface $pageFactory = null;

    /**
     * @param \Laminas\Log\Logger                          $logger
     * @param \Mezzio\Navigation\Page\PageFactoryInterface|null $pageFactory
     */
    public function __construct(Logger $logger, ?PageFactoryInterface $pageFactory)
    {
        $this->logger      = $logger;
        $this->pageFactory = $pageFactory;
    }

    /**
     * Converts a $mixed value to an array of pages
     *
     * @param int|array<int|string, array<string>|string>|AbstractPage|AbstractContainer|ContainerInterface|PageInterface|string|Traversable $mixed     mixed value to get page(s) from
     * @param bool                                                                                        $recursive whether $value should be looped if it is an array or a config
     *
     * @return array<int, PageInterface|AbstractPage>
     *
     * @throws \Laminas\Stdlib\Exception\InvalidArgumentException
     */
    public function convert($mixed, bool $recursive = true): array
    {
        if ($mixed instanceof PageInterface || $mixed instanceof AbstractPage) {
            // value is a page instance; return directly
            return [$mixed];
        }

        if ($mixed instanceof ContainerInterface) {
            // value is a container; return pages in it
            $pages = [];

            foreach ($mixed as $page) {
                $pages[] = $page;
            }

            return $pages;
        }

        if (is_string($mixed)) {
            // value is a string; make a URI page
            try {
                if (null !== $this->pageFactory) {
                    $page = $this->pageFactory->factory(
                        [
                            'type' => 'uri',
                            'uri' => $mixed,
                        ]
                    );
                } else {
                    $page = AbstractPage::factory(
                        [
                            'type' => 'uri',
                            'uri' => $mixed,
                        ]
                    );
                }

                return [$page];
            } catch (InvalidArgumentException | \Laminas\Navigation\Exception\InvalidArgumentException $e) {
                $this->logger->err($e);

                return [];
            }
        }

        if ($mixed instanceof Traversable) {
            $mixed = ArrayUtils::iteratorToArray($mixed);
        }

        if (is_array($mixed) && [] !== $mixed) {
            if ($recursive && is_numeric(key($mixed))) {
                // first key is numeric; assume several pages
                return array_map(
                    /**
                     * @return PageInterface|AbstractPage
                     */
                    function ($value) {
                        [$page] = $this->convert($value, false);

                        return $page;
                    },
                    $mixed
                );
            }

            // pass array to factory directly
            try {
                if (null !== $this->pageFactory) {
                    $page = $this->pageFactory->factory($mixed);
                } else {
                    $page = AbstractPage::factory($mixed);
                }

                return [$page];
            } catch (InvalidArgumentException | \Laminas\Navigation\Exception\InvalidArgumentException $e) {
                $this->logger->err($e);
            }
        }

        // nothing found
        return [];
    }
}

```

**Comment by mimmi20** [comment]
see also https://github.com/phpstan/phpstan/issues/5462
