### ISSUE TITLE
ShouldNotHappenException

### ISSUE THREAD

**Issue by Stadly** [pepakriz/phpstan-exception-rules#30]
Just got this error. Let me know if you need anything else to figure it out.

```
Fatal error: Uncaught PHPStan\ShouldNotHappenException: Internal error. in MyApp\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php:207
Stack trace:
#0 MyApp\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php(112): Pepakriz\PHPStanExceptionRules\Rules\ThrowsPhpDocRule->processMethodCall(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope))
#1 MyApp\vendor\phpstan\phpstan\src\Analyser\Analyser.php(128): Pepakriz\PHPStanExceptionRules\Rules\ThrowsPhpDocRule->processNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope))
#2 MyApp\vendor\phpstan\phpstan\src\Analyser\NodeScopeResolver.php(369): PHPStan\Analyser\Analyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope))
#3 MyApp\vendor\phpstan\phpstan\src\Analyser\NodeScopeResolver.php(903): PHPStan\Analyser\NodeScopeResolver->processNode(Object(Ph in MyApp\vendor\pepakriz\phpstan-exception-rules\src\Rules\ThrowsPhpDocRule.php on line 207
```

**Comment by pepakriz** [comment]
It can happen when a method is calling on an unknown class. I've fixed the internal error by skipping, but you should verify the place in your code where the error has occurred. Maybe you've defined wrong phpdoc or something...
