### ISSUE TITLE
ThrowsScope: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by ro0NL** [pepakriz/phpstan-exception-rules#65]
```
/app $ phpstan analyse --debug
Note: Using configuration file /app/phpstan.neon.
/app/.../Resources/config/form.php

Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in src/Rules/ThrowsScope.php:96
Stack trace:
#0 src/Rules/ThrowsScope.php(96): array_keys(NULL)
#1 src/Rules/ThrowsScope.php(82): Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->isExceptionCaught('Symfony\\Compone...')
#2 [internal function]: Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->Pepakriz\PHPStanExceptionRules\Rules\{closure}('Symfony\\Compone...')
#3 src/Rules/ThrowsScope.php(83): array_filter(Array, Object(Closure))
#4 src/Rules/ThrowsPhpDocRule.php(639): Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->filterExceptionsByUncaught(Array)
#5 ... in src/Rules/ThrowsScope.php on line 96
```

**Comment by pepakriz** [comment]
Probably duplication of https://github.com/pepakriz/phpstan-exception-rules/issues/64
